# Generated by Django 4.2.6 on 2023-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('punch_date', models.DateField()),
                ('in_time', models.TimeField()),
            ],
            options={
                'db_table': 'impr_attendance_table',
            },
        ),
    ]
