# Generated by Django 4.2.6 on 2023-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprAttendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('punch_date', models.DateField(blank=True, null=True)),
                ('card_no', models.TextField()),
                ('in_gate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_gate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('is_validate', models.CharField(max_length=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'impr_attendance_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
